server:
  port: 8090

spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: java1234
    jdbc-url: jdbc:mysql://localhost:3306/Dooolphin?serverTimezone=Asia/Seoul
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        show_sql : true
        format_sql : true
        use_sql_comments : true

logging:
  pattern:
    console: "[%d{yyyy-MM-dd HH:mm:ss.SSS}] %highlight([%-5level])  %green([%thread]) [%logger] %method : %msg%n"
  file:
    path: D:\logs
    name: D:\logs\baemin.log
  level:
    root: INFO
  logback:
    rollingpolicy:
      max-file-size: 1MB
      max-history: 7
      total-size-cap: 10MB
      file-name-pattern: "${LOG_FILE}.%d{yyyy-MM-dd}_%i.txt"

springdoc:
  packages-to-scan: baemin.controller
  swagger-ui:
    path: /swagger.html
