server:
  port: 8090

spring:
  config:
    activate:
      on-profile: local
  logging:
    pattern:
      file: "%-4relative [%thread] %-5level %logger{35} - %msg%n"
    logback:
      rollingpolicy:
        file-name-pattern: "${LOG_FILE}.%d{yyyy-MM-dd}_%i.text"
    file:
      path: D:\log
      max-history: 7
      max-size: 5KB
      total-size-cap: 1MB
    level:
      root: Info
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/Dooolphin?serverTimezone=Asia/Seoul
    username: root
    password: java1234
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        show_sql : true
        format_sql : true
        use_sql_comments : true

springdoc:
  packages-to-scan: baemin.controller
  swagger-ui:
    path: /swagger.html
